### ISSUE TITLE
Sound doesn't work in Safari

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Chimp-Zoo#72]
Videos are playing with no sound if watched in the Safari browser. (Ironic for a African wildlife project...)

This is true both in the classification interface and on Talk.

Example: you can clearly hear the hog grunting here: http://talk.chimpandsee.org/#/subjects/ACP0002rsh -- but Safari plays it silently.

**Comment by srallen** [comment]
Safari uses Quicktime for its codec support and so what is supported is varied on the OS X and Quicktime version that is installed. Those who are experiencing this could either use a different browser that isn't dependent on Quicktime (Firefox, Chrome) or could try installing a codec pack for Quicktime like Perian (at their own risk!).

**Comment by yshish** [comment]
Not Safari but Chrome on Yoga tablet. I can see the symbol for turning sound on/off, I can click on it but with no difference. It even doesn't allow me to set the volume. The sound works everywhere out of Chimp&See. Is it the same issue as the one reported on Safari?

**Comment by srallen** [comment]
@yshish, it may not exactly be the same issue, but may be similar in that whatever version of Chrome and Android is on your tablet may be missing the codec to play the audio properly. Since it's possible it's not a similar issue, though, could you open a separate issue ticket for this and include the Android version for your tablet?

**Comment by yshish** [comment]
Done! Thanks.
